#!/bin/sh

TEMPLATE_DIR=templates
THIS=`pwd`
EXTENSION=Extension

usage(){
    echo "usage: $0 <name>"
}

if [ -z $1 ];
then
  usage
  exit
fi

case `basename $0` in
    create)
	echo "Use this script as createext for new extension, or createapp for new app!"
	exit
    ;;

    createext)
HOME=${EXTENSION}/$1
UNAME=$(echo $1 | tr '[:lower:]' '[:upper:]')
mkdir -p ${HOME}/src
mkdir -p ${HOME}/include
mkdir -p ${HOME}/test
awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/ext.cbp > ${HOME}/$1.cbp
awk " { gsub(\"#!#UEXT_NAME#!#\",\"$UNAME\");
        gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " \
         $TEMPLATE_DIR/Makefile.ext > ${HOME}/$1.mk
cat <<EOF > ${HOME}/include/$1.h
#ifndef _${UNAME}_INCLUDED_
#define _${UNAME}_INCLUDED_
/* Module ${1} */

#endif
EOF
awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/ext.c > ${HOME}/src/$1.c
awk " { gsub(\"#!#UEXT_NAME#!#\",\"$UNAME\");
        gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " \
         $TEMPLATE_DIR/test/Makefile > ${HOME}/test/Makefile
awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/test/main.c > ${HOME}/test/main.c
awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/test/test.cbp > ${HOME}/test/$1.cbp

awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/test/chconf.h > ${HOME}/test/chconf.h
awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/test/halconf.h > ${HOME}/test/halconf.h
awk " { gsub(\"#!#EXT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/test/mcuconf.h > ${HOME}/test/mcuconf.h
    ;;

    createapp)
HOME=$1
mkdir ${HOME}
awk " { gsub(\"#!#PROJECT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/project.cbp > ${HOME}/$1.cbp
awk " { gsub(\"#!#PROJECT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/Makefile.app > ${HOME}/Makefile
awk " { gsub(\"#!#PROJECT_NAME#!#\",\"$1\"); print; } " $TEMPLATE_DIR/app.c > ${HOME}/main.c
cp $TEMPLATE_DIR/chconf.h ${HOME}
cp $TEMPLATE_DIR/halconf.h ${HOME}
cp $TEMPLATE_DIR/mcuconf.h ${HOME}
cp $TEMPLATE_DIR/misc.h ${HOME}
cp $TEMPLATE_DIR/misc.c ${HOME}
cp $TEMPLATE_DIR/usbcfg.h ${HOME}
cp $TEMPLATE_DIR/usbcfg.c ${HOME}
    ;;
esac

mkdir -p ${HOME}/doc
awk " { gsub(\"PROJECT_NAME +=\",\"PROJECT_NAME=$1\"); print; } " $TEMPLATE_DIR/doc/doxyfile > ${HOME}/doc/doxyfile
cp $TEMPLATE_DIR/.gitignore ${HOME}
cp $TEMPLATE_DIR/doc/Makefile ${HOME}/doc
cp $TEMPLATE_DIR/doc/.gitignore ${HOME}/doc
