#!/bin/sh

terminal=gtkterm
terminalparam="-c disc"

case $(basename $0) in
    killterm)
	term=`ps ax | grep ${terminal} | wc | awk '{print $1}'`
	echo $term
	if [ "$term" -eq "2" ]; 
	then
	    echo killing ${terminal}
	    killall ${terminal}
	fi
    ;;

    startterm)
	echo start terminal
	${terminal} ${terminalparam} &
    ;;

    *)
esac
